parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''
- name: aptPackages
  type: object
  default:
    - cmake
    - python3-pip
    - libnuma-dev
    - ninja-build
    - ccache

jobs:
- job: llvm_project
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  - name: HIP_DEVICE_LIB_PATH
    value: '$(Build.BinariesDirectory)/amdgcn/bitcode'
  pool: ${{ variables.CLOUD_BUILD_POOL }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
# CI case: download latest default branch build
  - ${{ if eq(parameters.checkoutRef, '') }}:
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
      parameters:
        componentName: rocm-cmake
        branchName: develop
        pipelineId: $(rocm-cmake-pipeline-id)
        testFailuresOkay: true
# manual build case: triggered by ROCm/ROCm repo
  - ${{ if ne(parameters.checkoutRef, '') }}:
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
      parameters:
        componentName: \tag-builds\rocm-cmake
        pipelineId: $(rocm-cmake-tagged-pipeline-id)
        testFailuresOkay: true
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      componentName: rocm-llvm
      extraBuildFlags: >-
        -DCMAKE_PREFIX_PATH="$(Build.BinariesDirectory)/llvm;$(Build.BinariesDirectory)"
        -DCMAKE_BUILD_TYPE=Release
        -DLLVM_ENABLE_PROJECTS="llvm;clang;lld;clang-tools-extra"
        -DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind"
        -DCLANG_ENABLE_AMDCLANG="ON"
        -DLLVM_TARGETS_TO_BUILD="AMDGPU;X86"
        -GNinja
      cmakeBuildDir: 'llvm/build'
      installDir: '$(Build.BinariesDirectory)/llvm'
# use llvm-lit to run unit tests for llvm, clang, and lld
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml
    parameters:
      componentName: check-llvm
      testDir: 'llvm/build'
      testExecutable: './bin/llvm-lit'
      testParameters: '-q --xunit-xml-output=llvm_test_output.xml ./test'
      testOutputFile: llvm_test_output.xml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml
    parameters:
      componentName: check-clang
      testDir: 'llvm/build'
      testExecutable: './bin/llvm-lit'
      testParameters: '-q --xunit-xml-output=clang_test_output.xml ./tools/clang/test'
      testOutputFile: clang_test_output.xml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml
    parameters:
      componentName: check-lld
      testDir: 'llvm/build'
      testExecutable: './bin/llvm-lit'
      testParameters: '-q --xunit-xml-output=lld_test_output.xml ./tools/lld/test'
      testOutputFile: lld_test_output.xml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      componentName: device-libs
      extraBuildFlags: >-
        -DCMAKE_PREFIX_PATH="$(Build.SourcesDirectory)/llvm/build"
        -DCMAKE_BUILD_TYPE=Release
      cmakeBuildDir: 'amd/device-libs/build'
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      componentName: comgr
      extraBuildFlags: >-
        -DCMAKE_PREFIX_PATH="$(Build.SourcesDirectory)/llvm/build;$(Build.SourcesDirectory)/amd/device-libs/build"
        -DCMAKE_BUILD_TYPE=Release
      cmakeBuildDir: 'amd/comgr/build'
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml
    parameters:
      componentName: comgr
      testParameters: '--output-on-failure --force-new-ctest-process --output-junit comgr_test_output.xml'
      testDir: 'amd/comgr/build'
      testOutputFile: comgr_test_output.xml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      componentName: hipcc
      extraBuildFlags: >-
        -DCMAKE_BUILD_TYPE=Release
        -DHIPCC_BACKWARD_COMPATIBILITY=OFF
      cmakeBuildDir: 'amd/hipcc/build'
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
