jobs:
- job: rocm_core
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool:
    vmImage: ${{ variables.LOW_END_BUILD_POOL }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
# ${{ }} are resolved during compile-time
# so this next step is skipped completely until
# we define explicit aptPackages needed to install
  - ${{ if parameters.aptPackages }}:
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies.yml
      parameters:
        aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      extraBuildFlags: >-
        -DCMAKE_CURRENT_BINARY_DIR=$PWD
        -DCMAKE_CURRENT_SOURCE_DIR=$PWD/../
        -DCMAKE_VERBOSE_MAKEFILE=1
        -DCPACK_GENERATOR=DEB
        -DCPACK_DEBIAN_PACKAGE_RELEASE="local.9999~99.99"
        -DCPACK_RPM_PACKAGE_RELEASE="local.9999"
        -DROCM_VERSION="$(last-release)"
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
