parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''
- name: aptPackages
  type: object
  default:
    - doxygen
    - doxygen-doc
    - ninja-build
    - python3-sphinx
- name: pipModules
  type: object
  default:
    - cget
    - ninja

jobs:
- job: rocm_cmake
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool:
    vmImage: ${{ variables.BASE_BUILD_POOL }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-other.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}
      pipModules: ${{ parameters.pipModules }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
# extra steps for ctest suite
  - script: |
      python -m pip install -r $(Build.SourcesDirectory)/docs/requirements.txt
      python -m pip install -r $(Build.SourcesDirectory)/test/docsphinx/docs/.sphinx/requirements.txt
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
    displayName: "ctest setup"
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml
    parameters:
      componentName: rocm-cmake
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
