parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''

jobs:
- job: rocprofiler_register
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  - name: system.debug
    value: 'true'
  pool:
    vmImage: ${{ variables.BASE_BUILD_POOL }}
  workspace:
    clean: all
  steps:
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
  #   parameters:
  #     checkoutRepo: ${{ parameters.checkoutRepo }}
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
  #   parameters:
  #     componentName: rocprofiler-register
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
  #   parameters:
  #     componentName: rocprofiler-register-tests
  #     extraBuildFlags: >-
  #       -DCMAKE_PREFIX_PATH=$(Build.BinariesDirectory)
  #     cmakeBuildDir: 'tests/build'
  #     installEnabled: false
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml
  #   parameters:
  #     componentName: rocprofiler-register
  #     testDir: 'tests/build'
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
  - task: Bash@3
    displayName: Create manifest
    inputs:
      targetType: 'inline'
      script: |
        cat <<EOF > $(Agent.BuildDirectory)/manifest1.xml
        <?xml version="1.0" encoding="UTF-8"?> <manifest> <component>this is an xml line 1</component> <component>this is an xml line 2</component> </manifest>
        EOF
        cat <<EOF > $(Agent.BuildDirectory)/manifest2.html
        <?xml version="1.0" encoding="UTF-8"?> <manifest> <component>this is an html line 1</component> <component>this is an html line 2</component> </manifest>
        EOF
  - task: PublishHtmlReport@1
    displayName: 'Publish manifest'
    continueOnError: true
    inputs:
      tabName: xml
      reportDir: $(Agent.BuildDirectory)/manifest1.xml
  - task: PublishHtmlReport@1
    displayName: 'Publish manifest'
    continueOnError: true
    inputs:
      tabName: html
      reportDir: $(Agent.BuildDirectory)/manifest2.html
  - bash: |
      echo "Build.BuildId: $(Build.BuildId)"
      echo "Build.BuildNumber: $(Build.BuildNumber)"
      echo "Build.SourceBranch: $(Build.SourceBranch)"
      echo "Build.SourceBranchName: $(Build.SourceBranchName)"
      echo "Build.SourceVersion: $(Build.SourceVersion)"
      echo "Build.SourceVersionMessage: $(Build.SourceVersionMessage)"
      echo "Build.DefinitionName: $(Build.DefinitionName)"
      echo "Build.Repository.ID: $(Build.Repository.ID)"
      echo "Build.Repository.Name: $(Build.Repository.Name)"
      echo "System.DefinitionId: $(System.DefinitionId)"
