parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''

jobs:
- job: rocprofiler_register
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  - name: system.debug
    value: 'true'
  pool:
    vmImage: ${{ variables.BASE_BUILD_POOL }}
  workspace:
    clean: all
  steps:
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
  #   parameters:
  #     checkoutRepo: ${{ parameters.checkoutRepo }}
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
  #   parameters:
  #     componentName: rocprofiler-register
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
  #   parameters:
  #     componentName: rocprofiler-register-tests
  #     extraBuildFlags: >-
  #       -DCMAKE_PREFIX_PATH=$(Build.BinariesDirectory)
  #     cmakeBuildDir: 'tests/build'
  #     installEnabled: false
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml
  #   parameters:
  #     componentName: rocprofiler-register
  #     testDir: 'tests/build'
  # - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/manifest.yml
