parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''
- name: aptPackages
  type: object
  default:
    - python3-pip
    - cmake
    - ninja-build
    - pkg-config
    - ffmpeg
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libva-dev
    - libdrm-dev
    - pybind11-dev
    - python3-pybind11
    - libdlpack-dev
- name: pipModules
  type: object
  default:
    - cibuildwheel
- name: rocmDependencies
  type: object
  default:
    - rocm-cmake
    - llvm-project
    - ROCR-Runtime
    - clr
    - rocminfo
    - rocm-core
    - rocprofiler-register
    - rocDecode

jobs:
- job: rocPyDecode
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool:
    vmImage: ${{ variables.BASE_BUILD_POOL }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-other.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}
      pipModules: ${{ parameters.pipModules }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-rocm.yml
    parameters:
      dependencyList: ${{ parameters.rocmDependencies }}
      # CI case: download latest default branch build
      ${{ if eq(parameters.checkoutRef, 'develop') }}:
        dependencySource: staging
      # manual build case: triggered by ROCm/ROCm repo
      ${{ elseif ne(parameters.checkoutRef, 'develop') }}:
        dependencySource: tag-builds
  - task: Bash@3
    displayName: 'ROCm symbolic link'
    inputs:
      targetType: inline
      script: |
        sudo rm -rf /opt/rocm
        sudo ln -s $(Agent.BuildDirectory)/rocm /opt/rocm
#  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
#    parameters:
#      extraBuildFlags: >-
#        -DROCM_PATH=$(Agent.BuildDirectory)/rocm
#        -DCMAKE_PREFIX_PATH=$(Agent.BuildDirectory)/rocm
#        -DCMAKE_BUILD_TYPE=Release
#        -DAMDGPU_TARGETS=$(JOB_GPU_TARGET)
#        -DCMAKE_INSTALL_PREFIX_PYTHON=$(Build.BinariesDirectory)
#        -GNinja
#  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
#    parameters:
#      gpuTarget: $(JOB_GPU_TARGET)
#      publish: false
#  - task: Bash@3
#    displayName: Create wheel file
#    inputs:
#      targetType: inline
#      script: |
#        export ROCM_PATH=$(Agent.BuildDirectory)/rocm
#        export HIP_INCLUDE_DIRS=$(Agent.BuildDirectory)/rocm/include/hip
#        python3 setup.py bdist_wheel
#      workingDirectory: $(Build.SourcesDirectory)
#  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-prepare-package.yml
#    parameters:
#      sourceDir: $(Build.SourcesDirectory)/dist
#      contentsString: '*.whl'
#      targetDir: $(Build.ArtifactStagingDirectory)
#      clean: false
#  - task: PublishPipelineArtifact@1
#    displayName: 'wheel file Publish'
#    retryCountOnTaskFailure: 3
#    inputs:
#      targetPath: $(Build.ArtifactStagingDirectory)
  - task: Bash@3
    displayName: Create wheel file
    inputs:
      targetType: inline
      script: cibuildwheel --output-dir wheelhouse .
      workingDirectory: $(Build.SourcesDirectory)
    env:
      ROCM_PATH: $(Agent.BuildDirectory)/rocm
      CIBW_BEFORE_BUILD: python3 rocPyDecode-requirements.py
  - task: PublishPipelineArtifact@1
    displayName: 'wheel file Publish'
    retryCountOnTaskFailure: 3
    inputs:
      targetPath: wheelhouse

- job: rocPyDecode_testing
  dependsOn: rocPyDecode
  condition: and(succeeded(), eq(variables.ENABLE_GFX942_TESTS, 'true'))
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool: $(JOB_TEST_POOL)
  workspace:
    clean: all
  strategy:
    matrix:
      gfx942:
        JOB_GPU_TARGET: gfx942
        JOB_TEST_POOL: ${{ variables.GFX942_TEST_POOL }}
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-other.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/local-artifact-download.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-aqlprofile.yml
    parameters:
      ${{ if eq(parameters.checkoutRef, '') }}:
        dependencySource: staging
      ${{ elseif ne(parameters.checkoutRef, '') }}:
        dependencySource: tag-builds
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-rocm.yml
    parameters:
      dependencyList: ${{ parameters.rocmDependencies }}
      gpuTarget: $(JOB_GPU_TARGET)
      ${{ if eq(parameters.checkoutRef, '') }}:
        dependencySource: staging
      ${{ elseif ne(parameters.checkoutRef, '') }}:
        dependencySource: tag-builds
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
  - task: Bash@3
    displayName: Setup test environment
    inputs:
      targetType: inline
      script: |
        sudo rm -rf /opt/rocm
        sudo ln -s $(Agent.BuildDirectory)/rocm /opt/rocm
        cd $(Build.SourcesDirectory)
        sudo pip install .
        cmake -DAMDGPU_TARGETS=$(JOB_GPU_TARGET) .
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml
    parameters:
      componentName: rocPyDecode
      testDir: $(Build.SourcesDirectory)
# sudo required for pip install but screws up permissions for next pipeline run
  - task: Bash@3
    displayName: Clean up test environment
    inputs:
      targetType: inline
      script: |
        sudo rm -rf $(Build.SourcesDirectory)/*
