parameters:
- name: aptPackages
  type: string
  default: 'libelf-dev g++ libdrm-dev libnuma-dev'

jobs:
- job: ROCR_Runtime
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool:
    vmImage: ${{ variables.LOW_END_BUILD_POOL }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
# ${{ }} are resolved during compile-time
# so this next step is run because
# we define explicit aptPackages needed to install
  - ${{ if parameters.aptPackages }}:
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies.yml
      parameters:
        aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
    parameters:
      componentName: llvm-project
      branchName: amd-staging
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
    parameters:
      componentName: ROCT-Thunk-Interface
      branchName: master
  - script: 'ls -1R $(Agent.BuildDirectory)/rocm'
    displayName: 'Artifact listing'
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      extraBuildFlags: >-
        -DCMAKE_PREFIX_PATH="$(Agent.BuildDirectory)/rocm"
      cmakeBuildDir: 'src/build'
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
